### ISSUE TITLE
Can not set type on listen

### ISSUE THREAD

**Issue by lyquocnam** [marcojakob/dart-event-bus#14]
i have code like this:
```dart
class AccountPhotoChangeEvent {
  final File file;
  AccountPhotoChangeEvent(this.file);
}
```
if i try register event like this:
```dart
events.on(AccountPhotoChangeEvent).listen((AccountPhotoChangeEvent event) {
      
});
```
and error
`The argument type '(AccountPhotoChangeEvent) → Null' can't be assigned to the parameter type '(dynamic) → void'.`

**Comment by marcojakob** [comment]
I've updated the package for Dart 2.0 and released [version 1.0.0 of event_bus on pub](https://pub.dartlang.org/packages/event_bus). I think this should fix your problem but you will have to change the way you call the `on` method because the API changed for 1.0.0:

```
events.on<AccountPhotoChangeEvent>().listen((event) {
   // do something with the event.   
});
```

**Comment by lyquocnam** [comment]
flutter's dart standard is `2.0.0-dev.58.0.flutter-f981f09760` can this work ?
is see this message: `Because hospital depends on event_bus >=1.0.0 which requires SDK version >=2.0.0-dev.67.0 <2.0.0, version solving failed.
pub get failed (1)`
Can you set dependency to `2.0.0-dev.58.0.flutter-f981f09760` comfortable with flutter please ?

**Comment by marcojakob** [comment]
@lyquocnam You could try to do this with a dependency override: https://www.dartlang.org/tools/pub/dependencies#dependency-overrides

**Comment by lyquocnam** [comment]
sorry but still not work

**Comment by lyquocnam** [comment]
ya it work like a charm, thanks author so much !
