### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by gedw99** [marcojakob/dart-event-bus#16]
This pattern looks good for flutter.
I know bloc pattern is the recommended way with flutter but I have to do code reuse and so event bus is a better fit for my use case.

Has anyone tried this ?

**Comment by marcojakob** [comment]
I would love to do more with Flutter but right now I don't have much experience with it and can't help you in regards to recommended patterns with Flutter.

But you can use the `EventBus` for various patterns. You don't have to use it with MVC as described in the readme. It's just a way for components to communicate.

**Comment by rravithejareddy** [comment]
I am unable use it in flutter, they are not like a classes, can you help us please!

**Comment by marcojakob** [comment]
Can you be a bit more specific on what does not work with `EventBus` in Flutter? 

Is it similar to the issue #19 ?
