### ISSUE TITLE
Flutter: listening callback not be called

### ISSUE THREAD

**Issue by Julyyq** [marcojakob/dart-event-bus#19]
In my "HomePage" `initState` function, I place the following code for listening to `NewOrderEvent`:

```
import '../eventbus/eventbus.dart';
.....
@override
void initState() {
  super.initState();
  eventBus.on<NewOrderEvent>().listen((event) {
    print("event fired: $event");
  });
}
```

These code works fine and in `main.dart` file, I invoke `eventBus.fire(new NewOrderEvent("some data");` when my app receive message from Firebase Cloud Message,   the `eventBus.fire` function is indeed be invoked, but the listen callback function not be called.

This is my "eventbus.dart" file content:

```
import 'package:event_bus/event_bus.dart';

EventBus eventBus = new EventBus();

class NewOrderEvent {
  Map order;

  NewOrderEvent(this.order);
}
```

I print the `firing eventBus object` and `listening eventBus object`: 
![screenshot 2018-12-09 17 47 57](https://user-images.githubusercontent.com/2620575/49695756-b604a480-fbda-11e8-8bb0-c98690341d43.png)

They are indeed the same object. 

BTW, the following are property and methods of the eventBus object:
![screenshot 2018-12-09 17 53 36](https://user-images.githubusercontent.com/2620575/49695822-8013f000-fbdb-11e8-9690-9b5f5a755e8c.png)

**Comment by Julyyq** [comment]
I solve the problem, seems that there is a bug of attaching Map data to the event.

![screenshot 2018-12-09 18 25 52](https://user-images.githubusercontent.com/2620575/49696137-4e515800-fbe0-11e8-9a70-20f66433ef8d.png)

**Comment by rravithejareddy** [comment]
Is it solved?

**Comment by marcojakob** [comment]
Reopening this because there seems to be an issue (also see #16), although I don't quite understand it yet. If someone could clarify, it would be great.

**Comment by Julyyq** [comment]
@marcojakob My problem is that passing `Map` type data to the listener, the listener function cannot be called.

**Comment by JordyBaylac** [comment]
> Reopening this because there seems to be an issue (also see #16), although I don't quite understand it yet. If someone could clarify, it would be great.

Why is it opened if it is not clear that #16 has same issue than this?

**Comment by marcojakob** [comment]
@JordyBaylac Do you also have an issue with event bus and flutter?

**Comment by rio45ka** [comment]
> Is it solved? I need a sample example in flutter using EventBus in different widget class (Other than main), that would be a great for flutter people.

@marcojakob can you give example?

**Comment by JordyBaylac** [comment]
@marcojakob no I am not having any issue so far.

**Comment by rravithejareddy** [comment]
> > Is it solved? I need a sample example in flutter using EventBus in different widget class (Other than main), that would be a great for flutter people.
> 
> @marcojakob can you give example?

No actually, i misunderstood flutter flow that's why i don't need event-bus now, event bus is needed for particular scenarios, at present we are not using it. Thanks for your support.

**Comment by marcojakob** [comment]
I'll close this since the problem seems to not be the event bus but something else.

**Comment by uchiha-itachi95** [comment]
I am also facing the same issue. I am also firing one event on message from Firebase. The listener is another screen which is pushed over the screen which is actually sending the event.

Strange enough, if I send event from screen A to Screen B (screen B is a BottomNavigationBarItem) it works. But if screen B is another screen which is pushed onto screen A, it does not work.

Above the author said it does not support Map data. But I am sending basic `int` data. That also seems not to work.

**Comment by marcojakob** [comment]
@uchiha-itachi95 Please check that you are using the same instance of your EventBus.

**Comment by yahu1031** [comment]
@marcojakob I am facing the same issue with the latest version. The data is being intermittently gathered. I have a similar scenario: I have an event bus listener on page `A` (where it works fine). And now I have 1-2 pages stacked or pushed over page `A`. And I have an same instance event bus listener which listens to the same event in page `B`(which gets data intermittently). Hope this will get a fix or a solution(work around).
