### ISSUE TITLE
Support stick events？

### ISSUE THREAD

**Issue by wdp1990821** [marcojakob/dart-event-bus#23]

**Comment by marcojakob** [comment]
What do you mean by that?

**Comment by ozyl** [comment]
After sending the event, the newly registered listener can receive the event。Hope to support it。

**Comment by marcojakob** [comment]
Maybe you could provide your own custom stream controller that has dis behavior: https://github.com/marcojakob/dart-event-bus#using-custom-stream-controllers

Also have a look at Darts [async package](https://pub.dev/packages/async). Maybe you'll find some things you can reuse from that.

**Comment by ozyl** [comment]
Thank you, use `EventBus.customController (BehaviorSubject ())`can achieve this effect.

**Comment by ozyl** [comment]
thanks for the reply,use `EventBus.customController (BehaviorSubject ()) ;`can achieve this effect.

**Comment by sunnykinger** [comment]
> thanks for the reply,use `EventBus.customController (BehaviorSubject ()) ;`can achieve this effect.

how to remove that event from the bus?
