### ISSUE TITLE
suggestion : widget for rebuild when event arrived

### ISSUE THREAD

**Issue by DJafari** [marcojakob/dart-event-bus#27]
i think this package need to have a Widget for rebuild tree when an event received

something like this :

```dart
BusBuilder<String>(
  builder: (BuildContext context, String event) {
                        
  }
),
```

**Comment by JordyBaylac** [comment]
do the change an open a PR @DJafari . but also think about the subscription cancellation. If BusBuilder get subscribed then you allow unsubscribing in someway

**Comment by subzero911** [comment]
> i think this package need to have a Widget for rebuild tree when an event received

You can subscribe in initState() and unsubscribe in dispose()
You'd better rebuild with state management solutions like Provider+ChangeNotifier or BLoC Library.
