### ISSUE TITLE
发起通知一次，注册接受的地方收到两次通知。

### ISSUE THREAD

**Issue by cuixiaodong** [marcojakob/dart-event-bus#30]
发起通知一次，注册接受的地方收到两次通知。

**Comment by marcojakob** [comment]
Hmmm, anyone knowing Chinese wants to tackle this?

**Comment by hualong-shen** [comment]
> Hmmm, anyone knowing Chinese wants to tackle this?

He is saying "When posting one event, the callback is called twice.", in case you are still interested in. @marcojakob

**Comment by marcojakob** [comment]
thanks @hualong-shen. 

@cuixiaodong I don't think this is an issue with the event bus. Probably you are registering yourself more than once to the same stream.
