### ISSUE TITLE
Is it a method off to  unregister event listener needed?

### ISSUE THREAD

**Issue by wahello** [marcojakob/dart-event-bus#33]
### Is it a method off or called something else to  unregister event listener needed? Just for something leak. I'm a newer to dart/flutter, so asked such a question.

**Comment by marcojakob** [comment]
Here is an example of how you can cancel the listener:

```
StreamSubscription loginSubscription = eventBus.on<UserLoggedInEvent>().listen((event) {
  print(event.user);
});

loginSubscription.cancel();
```
