### ISSUE TITLE
Are there plans to support flutter_web?

### ISSUE THREAD

**Issue by disburden** [marcojakob/dart-event-bus#34]
as title

**Comment by marcojakob** [comment]
I haven't tried it. Does it not work like this? The event bus needs very little to work: Dart Streams and some generic types. See https://github.com/marcojakob/dart-event-bus/blob/master/lib/event_bus.dart

**Comment by disburden** [comment]
Yes, it doesn't work in flutter_web project, I have n’t even started using it, I just import it at the top of the file, and I got the following error message:
```
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:event_bus/event_bus.dart';` from ...
PageWorks.dart at 8:1

Failed after 193ms
```

**Comment by marcojakob** [comment]
How does your `pubspec.yaml` look like? Here is how to install it: https://pub.dev/packages/event_bus#-installing-tab-

**Comment by marcojakob** [comment]
Ok, closing this as we didn't receive any further info.

**Comment by disburden** [comment]
Sorry, I have forgotten to reply due to the progress of the project in the past few days.

My project uses a lot of other dependent libraries, it seems that the configuration method is the same. I do n’t think there will be any problems in installation, otherwise my "import" statement should be a problem, rather than reporting an error at runtime

However, if other users do not encounter problems, I think it may be related to my computer or environment. I will try again when I have time.
thank you for your reply!
