### ISSUE TITLE
Create a new stream every time on() is called? 

### ISSUE THREAD

**Issue by hualong-shen** [marcojakob/dart-event-bus#35]
```
  Stream<T> on<T>() {
    if (T == dynamic) {
      return streamController.stream;
    } else {
      return streamController.stream.where((event) => event is T).cast<T>();
    }
  }
```
It seems every time when I subscribe a specific event type, it will create a new broadcast stream. Since it is broadcast stream, why not cache it by event type and reuse it? @marcojakob

**Comment by marcojakob** [comment]
Good question. You are right that the `where` function creates a new stream on top of the original stream every time the `on` function is called (with a non-dynamic type).

Of course it would be possible to do caching but I don't think it's worth the added complexity. If this actually is a problem in your application (you should measure it) then it would probably be better to just create your own custom event bus specific to your need. But I think it's very unlikely that you will need this as I can't think of a use case where you would register to the event bus so many times. Usually it's just a few components talking with each other.
