### ISSUE TITLE
hi! The release version does not work

### ISSUE THREAD

**Issue by momtboy** [marcojakob/dart-event-bus#41]
The debug version can work normally, but after the release version is packaged, it is found not to work. What is the problem?

**Comment by marcojakob** [comment]
Are you sure this is about the event bus? Maybe it's something else that doesn't work. If you still think it's the event bus you should provide more details and (minimal) code so that someone could reproduce the problem.

**Comment by artem-bakuta** [comment]
same issue, app frizzes on star when using release

**Comment by chrigu-ebert** [comment]
@momtboy or @artem-bakuta Can you provide a minimal code example? I just installed the latest version and it runs without issues.
