### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by len8657** [marcojakob/dart-event-bus#44]
[√] Flutter (Channel dev, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.18363.1256], locale zh-CN)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.3)
[!] Android Studio (not installed)
[√] VS Code (version 1.52.1)
[√] Connected device (3 available)

! Doctor found issues in 2 categories.

Flutter channels:
  master
* dev
  stable

**Comment by marcojakob** [comment]
Is this really an `event_bus` problem? Can you be more specific what you are doing with `event_bus`?

**Comment by len8657** [comment]
> _No description provided._

**Comment by len8657** [comment]
> Is this really an `event_bus` problem? Can you be more specific what you are doing with `event_bus`?
it's my problem, i closed this issue
