### ISSUE TITLE
有时候同时调用两个事件fire会失效

### ISSUE THREAD

**Issue by wengxianxun** [marcojakob/dart-event-bus#45]
EventBusUtil.fire(
              AudioAnimationIcon_animation_event(playerState: state)); EventBusUtil.fire(AudioStylus_animation_event(ynAnimation: false));

同时调用这两个事件，listen的地方接收不到

**Comment by marcojakob** [comment]
Sorry, don't understand. Please write your error report in English.

**Comment by amoslai5128** [comment]
I think he meant if he fires two events at the same time, the state didn't listen to any updates.
