### ISSUE TITLE
event from callback of top level function 

### ISSUE THREAD

**Issue by nagyhero** [marcojakob/dart-event-bus#47]
> now i'm using foreground service with call back top level function .. and using a singleton class for both BackgroundTaskManger and EventBusManger when i receive an event from TaskManger can debugPrint a data but when i use EventBus fire cannot getting the event in any part of my code with on.listen .

- are any solution  with same this package or need another way to use send data in isolate ?

**Comment by marcojakob** [comment]
This doesn't sound like a problem with EventBus. There is probably something not correct in the way you access your singleton. Maybe it's not a singleton and you have two instances.

**Comment by nagyhero** [comment]
> This doesn't sound like a problem with EventBus. There is probably something not correct in the way you access your singleton. Maybe it's not a singleton and you have two instances.

thanks for you replay , i already print some index in singleton and sure to create one instance for event

**Comment by tigrenok00** [comment]
@nagyhero  Hi, have you found the problem/solution? I also have a singleton but from top level function it doesn't seem to work...
