### ISSUE TITLE
Event Bus not listening any event if i minimized the app Fcm come in background Fire an event but not listening any 

### ISSUE THREAD

**Issue by Ahmadgnoor** [marcojakob/dart-event-bus#50]
Please Guid me

**Comment by marcojakob** [comment]
We can't provide debugging support of an application. It is very unlikely this is caused by EventBus.

**Comment by Ammar-Ishfaq** [comment]
did they resolve this? as I'm not able to have the event listening on main widget from service (i.e: FCM)
