### ISSUE TITLE
Last update is 3 years ago. Is this package still safe to use? 

### ISSUE THREAD

**Issue by kyungilcho** [marcojakob/dart-event-bus#54]
I am wondering that this package is still safe to use even though its last update was 3 years ago and flutter has been through many breaking changes this and last year.

**Comment by marcojakob** [comment]
Good question... I'd also ask that. My answer: There is only very little code in `dart-event-bus`. Just a few lines in [`event_bus.dart`](https://github.com/marcojakob/dart-event-bus/blob/master/lib/event_bus.dart). You can have a look at it and see what it's doing and if there is a change in Dart/Flutter, it should be easy to adjust or just copy this file and change it how you like.

**Comment by xljhd** [comment]
Can you update to a version that supports Dart 3.0 or above?

**Comment by felixkriechbaum** [comment]
Our company uses the package in the latest version that is online and it works perfectly. Our sdk target is: “>=3.0.3 <4.0.0”

**Comment by marcojakob** [comment]
I've updated the sdk dependency in the new version 2.0.1.
